import enum

class Country(enum.Enum):
    Australia = "Australia"
    Austria = "Austria"
    Belgium = "Belgium"
    Bulgaria = "Bulgaria"
    Cyprus = "Cyprus"
    CzechRepublic = "CzechRepublic"
    Denmark = "Denmark"
    Finland = "Finland"
    France = "France"
    Germany = "Germany"
    Gibraltar = "Gibraltar"
    Greece = "Greece"
    Hungary = "Hungary"
    Ireland = "Ireland"
    Italy = "Italy"
    Latvia = "Latvia"
    Liechtenstein = "Liechtenstein"
    Lithuania = "Lithuania"
    Luxembourg = "Luxembourg"
    Malta = "Malta"
    Netherlands = "Netherlands"
    Norway = "Norway"
    Poland = "Poland"
    Portugal = "Portugal"
    Romania = "Romania"
    Slovakia = "Slovakia"
    Slovenia = "Slovenia"
    Spain = "Spain"
    Sweden = "Sweden"
    Switzerland = "Switzerland"
    UnitedKingdom = "UnitedKingdom"
