export const Country = {
  Australia: "🇦🇺 Australia",
  Austria: "🇦🇹 Austria",
  Belgium: "🇧🇪 Belgium",
  Bulgaria: "🇧🇬 Bulgaria",
  Cyprus: "🇨🇾 Cyprus",
  CzechRepublic: "🇨🇿 Czech Republic",
  Denmark: "🇩🇰 Denmark",
  Finland: "🇫🇮 Finland",
  France: "🇫🇷 France",
  Germany: "🇩🇪 Germany",
  Gibraltar: "🇬🇮 Gibraltar",
  Greece: "🇬🇷 Greece",
  Hungary: "🇭🇺 Hungary",
  Ireland: "🇮🇪 Ireland",
  Italy: "🇮🇹 Italy",
  Latvia: "🇱🇻 Latvia",
  Liechtenstein: "🇱🇮 Liechtenstein",
  Lithuania: "🇱🇹 Lithuania",
  Luxembourg: "🇱🇺 Luxembourg",
  Malta: "🇲🇹 Malta",
  Netherlands: "🇳🇱 Netherlands",
  Norway: "🇳🇴 Norway",
  Poland: "🇵🇱 Poland",
  Portugal: "🇵🇹 Portugal",
  Romania: "🇷🇴 Romania",
  Slovakia: "🇸🇰 Slovakia",
  Slovenia: "🇸🇮 Slovenia",
  Spain: "🇪🇸 Spain",
  Sweden: "🇸🇪 Sweden",
  Switzerland: "🇨🇭 Switzerland",
  UnitedKingdom: "🇬🇧 United Kingdom",
} as const;

export type Country = (typeof Country)[keyof typeof Country];