export const Country = {
  Australia: "🇦🇺 Australia",
  Austria: "🇦🇹 Austria",
  Belgium: "🇧🇪 Belgium",
  Brazil: "🇧🇷 Brazil",
  Bulgaria: "🇧🇬 Bulgaria",
  Canada: "🇨🇦 Canada",
  Cyprus: "🇨🇾 Cyprus",
  CzechRepublic: "🇨🇿 Czech Republic",
  Denmark: "🇩🇰 Denmark",
  Estonia: "🇪🇪 Estonia",
  Finland: "🇫🇮 Finland",
  France: "🇫🇷 France",
  Germany: "🇩🇪 Germany",
  Ghana: "🇬🇭 Ghana",
  Gibraltar: "🇬🇮 Gibraltar",
  Greece: "🇬🇷 Greece",
  HongKong: "🇭🇰 Hong Kong",
  Hungary: "🇭🇺 Hungary",
  India: "🇮🇳 India",
  Indonesia: "🇮🇩 Indonesia",
  Ireland: "🇮🇪 Ireland",
  Italy: "🇮🇹 Italy",
  Japan: "🇯🇵 Japan",
  Kenya: "🇰🇪 Kenya",
  Latvia: "🇱🇻 Latvia",
  Liechtenstein: "🇱🇮 Liechtenstein",
  Lithuania: "🇱🇹 Lithuania",
  Luxembourg: "🇱🇺 Luxembourg",
  Malta: "🇲🇹 Malta",
  Mexico: "🇲🇽 Mexico",
  Netherlands: "🇳🇱 Netherlands",
  NewZealand: "🇳🇿 New Zealand",
  Norway: "🇳🇴 Norway",
  Poland: "🇵🇱 Poland",
  Portugal: "🇵🇹 Portugal",
  Romania: "🇷🇴 Romania",
  Singapore: "🇸🇬 Singapore",
  Slovakia: "🇸🇰 Slovakia",
  Slovenia: "🇸🇮 Slovenia",
  Spain: "🇪🇸 Spain",
  Sweden: "🇸🇪 Sweden",
  Switzerland: "🇨🇭 Switzerland",
  Thailand: "🇹🇭 Thailand",
  UnitedArabEmirates: "🇦🇪 United Arab Emirates",
  UnitedKingdom: "🇬🇧 United Kingdom",
  UnitedStates: "🇺🇸 United States",
  Uruguay: "🇺🇾 Uruguay"
} as const;

export type Country = (typeof Country)[keyof typeof Country];