---
- name: Install AWS CLI and login to ECR
  hosts: webservers
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Download AWS CLI v2 bundle
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI bundle
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Authenticate Docker to AWS ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region.value }} | docker login --username AWS --password-stdin {{ aws_account_id.value }}.dkr.ecr.{{ aws_region.value }}.amazonaws.com

      environment:
        AWS_REGION: "{{ aws_region.value }}"


