"""empty message

Revision ID: 0de8d8a7789e
Revises: 0284d13bb1f8
Create Date: 2025-09-04 13:51:38.899359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de8d8a7789e'
down_revision: Union[str, None] = '0284d13bb1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('youtube_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creator_profiles', 'youtube_url')
    # ### end Alembic commands ###
