"""empty message

Revision ID: 65438b3434a2
Revises: 67115508682b
Create Date: 2025-09-05 15:09:40.020516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65438b3434a2'
down_revision: Union[str, None] = '67115508682b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tips', 'name')
    # ### end Alembic commands ###
