"""empty message

Revision ID: 67115508682b
Revises: 0de8d8a7789e
Create Date: 2025-09-05 09:50:25.561469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67115508682b'
down_revision: Union[str, None] = '0de8d8a7789e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('youtube_channel_name', sa.String(), nullable=True))
    op.drop_column('creator_profiles', 'youtube_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('youtube_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('creator_profiles', 'youtube_channel_name')
    # ### end Alembic commands ###
