"""make tip private name to isPrivate

Revision ID: 839cb4d39b37
Revises: cebe5eb19c34
Create Date: 2025-08-13 12:11:25.645890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839cb4d39b37'
down_revision: Union[str, None] = 'cebe5eb19c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('isPrivate', sa.Boolean(), nullable=False))
    op.drop_column('tips', 'private')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tips', 'isPrivate')
    # ### end Alembic commands ###
