"""Add stripe_session_id to tips

Revision ID: 9197d56f2947
Revises: 956b6d4391d7
Create Date: 2025-08-07 23:24:07.404247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9197d56f2947'
down_revision: Union[str, None] = '956b6d4391d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('stripe_session_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tips', ['stripe_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tips', type_='unique')
    op.drop_column('tips', 'stripe_session_id')
    # ### end Alembic commands ###
