"""empty message

Revision ID: a3c695737466
Revises: c2912b9fcc03
Create Date: 2025-09-09 09:35:26.962997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c695737466'
down_revision: Union[str, None] = 'c2912b9fcc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('is_bank_connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('creator_profiles', 'is_bank_connected')
    # ### end Alembic commands ###
