"""empty message

Revision ID: bd8fc7df9abb
Revises: 
Create Date: 2025-08-05 16:03:12.967161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8fc7df9abb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('auth_provider', sa.Enum('PASSWORD', 'GOOGLE', name='authprovider'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_email'), 'creators', ['email'], unique=True)
    op.create_index(op.f('ix_creators_id'), 'creators', ['id'], unique=False)
    op.create_index(op.f('ix_creators_username'), 'creators', ['username'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    op.create_table('creator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('stripe_account_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id')
    )
    op.create_index(op.f('ix_creator_profiles_id'), 'creator_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creator_profiles_id'), table_name='creator_profiles')
    op.drop_table('creator_profiles')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_creators_username'), table_name='creators')
    op.drop_index(op.f('ix_creators_id'), table_name='creators')
    op.drop_index(op.f('ix_creators_email'), table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
