"""empty message

Revision ID: c2912b9fcc03
Revises: 65438b3434a2
Create Date: 2025-09-08 15:43:25.471981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2912b9fcc03'
down_revision: Union[str, None] = '65438b3434a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('profile_picture_key', sa.String(), nullable=True))
    op.add_column('creator_profiles', sa.Column('profile_banner_key', sa.String(), nullable=True))
    op.drop_column('creator_profiles', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator_profiles', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('creator_profiles', 'profile_banner_key')
    op.drop_column('creator_profiles', 'profile_picture_key')
    # ### end Alembic commands ###
