name: Deploy App

on:
  push:
    branches: [main]

jobs:
  terraform:
    name: Terraform Infrastructure
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      FRONTEND_ECR_URL: ${{ steps.tf_output.outputs.frontend_ecr_url }}
      BACKEND_ECR_URL: ${{ steps.tf_output.outputs.backend_ecr_url }}

    env:
      AWS_REGION: 'eu-west-2'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: deployment/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: deployment/terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: deployment/terraform

      - name: Terraform Output
        id: tf_output
        run: |
          echo "frontend_ecr_url=$(terraform output -raw frontend_ecr_url  | tr -d '\r\n')" >> $GITHUB_OUTPUT
          echo "backend_ecr_url=$(terraform output -raw backend_ecr_url | tr -d '\r\n')" >> $GITHUB_OUTPUT
        working-directory: deployment/terraform

  docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs: terraform

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: 'eu-west-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Echo ECR URLs
        run: |
          echo "Frontend: ${{ needs.terraform.outputs.FRONTEND_ECR_URL }}"
          echo "Backend: ${{ needs.terraform.outputs.BACKEND_ECR_URL }}"

      - name: Build and Push Frontend
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ needs.terraform.outputs.FRONTEND_ECR_URL }}:latest \
            --push ./frontend

      - name: Build and Push Backend
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ needs.terraform.outputs.BACKEND_ECR_URL }}:latest \
            --push ./backend

 
