name: Deploy App

on:
  push:
    branches: [main]

jobs:
  set-up:
    name: Set up
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: 'eu-west-2'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve
        working-directory: deployment/terraform

      - name: Store ECR URLS from Terraform output
        id: tf_output
        run: |
          echo "FRONTEND_ECR_URL=$(terraform output -raw frontend_ecr_url)" >> $GITHUB_OUTPUT
          echo "BACKEND_ECR_URL=$(terraform output -raw backend_ecr_url)" >> $GITHUB_OUTPUT
        working-directory: deployment/terraform

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ steps.tf_output.outputs.FRONTEND_ECR_URL }}:latest \
            --push ./frontend

      - name: Build and Push Backend
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ steps.tf_output.outputs.BACKEND_ECR_URL }}:latest \
            --push ./backend

 
